# Generated by Django 3.0.8 on 2021-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210224_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'technology'), ('entertainment', 'entertainment'), ('lifestyle', 'lifestyle'), ('other', 'other')], default='other', max_length=15),
        ),
    ]
